package com.localzet.floortrace.positioning

data class PositionCandidate(
    val source: String,
    val latitude: Double,
    val longitude: Double,
    val accuracyMeters: Float,
    val timestampMillis: Long,
)

data class PositionSnapshot(
    val latitude: Double? = null,
    val longitude: Double? = null,
    val approximateLatitude: Double? = null,
    val approximateLongitude: Double? = null,
    val provider: String = "—",
    val horizontalAccuracyMeters: Float? = null,
    val altitudeMeters: Double? = null,
    val verticalAccuracyMeters: Float? = null,
    val meanSeaLevelAltitudeMeters: Double? = null,
    val meanSeaLevelAltitudeAccuracyMeters: Float? = null,
    val speedMetersPerSecond: Float? = null,
    val bearingDegrees: Float? = null,
    val headingDegrees: Float? = null,
    val pitchDegrees: Float? = null,
    val rollDegrees: Float? = null,
    val pressureHpa: Float? = null,
    val relativeAltitudeMeters: Double? = null,
    val floor: Int? = null,
    val floorConfidence: Float = 0f,
    val floorCalibrated: Boolean = false,
    val satellitesVisible: Int = 0,
    val satellitesUsed: Int = 0,
    val averageCn0DbHz: Float? = null,
    val rawMeasurementCount: Int = 0,
    val steps: Long = 0,
    val magneticFieldMicroTesla: Float? = null,
    val gyroRateRadPerSec: Float? = null,
    val linearAccelerationMetersPerSecondSquared: Float? = null,
    val stepDetectorAvailable: Boolean = false,
    val pressureSensorAvailable: Boolean = false,
    val rotationVectorAvailable: Boolean = false,
    val rttSupported: Boolean = false,
    val rttAvailable: Boolean = false,
    val rttConfiguredAnchors: Int = 0,
    val rttRangedAnchors: Int = 0,
    val rttAccuracyMeters: Float? = null,
    val rejectedLocationCount: Int = 0,
    val lastLocationRejection: String? = null,
    val locationTimestampMillis: Long? = null,
    val candidates: List<PositionCandidate> = emptyList(),
    val timestampMillis: Long = System.currentTimeMillis(),
)
